services:
  - type: web
    name: neko-media-downloader-bot
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ALLOWED_USERS
        sync: false
